# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 434)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.l1 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setScaledContents(False)
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("label")
        self.horizontalLayout.addWidget(self.l1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.l4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.l4.setFont(font)
        self.l4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.l4)
        self.cb1 = QtWidgets.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.cb1.setFont(font)
        self.cb1.setEditable(True)
        self.cb1.setCurrentText("")
        self.cb1.setObjectName("comboBox")
        import sqlite3
        cts = sqlite3.connect("Fantasy_cricket.db")
        sql = "SELECT Name FROM teams"
        exc = cts.execute(sql)
        teams = []
        for rec in exc:
            self.cb1.addItem(rec[0])
        self.horizontalLayout_2.addWidget(self.cb1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.l5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.l5.setFont(font)
        self.l5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.l5)
        self.cb2 = QtWidgets.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.cb2.setFont(font)
        self.cb2.setEditable(True)
        self.cb2.setCurrentText("")
        self.cb2.setMaxVisibleItems(20)
        self.cb2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.cb2.setObjectName("comboBox_2")
        self.cb2.addItem("Match 1")
        self.cb2.addItem("Match 2")
        self.cb2.addItem("Match 3")
        self.cb2.addItem("Match 4")
        self.cb2.addItem("Match 5")
        self.horizontalLayout_2.addWidget(self.cb2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.l2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.l2.setFont(font)
        self.l2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.l2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.l3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.l3.setFont(font)
        self.l3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.l3)
        self.le1 = QtWidgets.QLineEdit(Dialog)
        self.le1.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.le1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lw1 = QtWidgets.QListWidget(Dialog)
        self.lw1.setObjectName("listWidget")
        self.horizontalLayout_5.addWidget(self.lw1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.lw2 = QtWidgets.QListWidget(Dialog)
        self.lw2.setObjectName("listWidget2")
        self.horizontalLayout_5.addWidget(self.lw2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.pbtn = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pbtn.setFont(font)
        self.pbtn.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pbtn)
        self.pbtn.clicked.connect(self.calcScore)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.l1.setText(_translate("Dialog", "Evaluate the Performance of your Fantasy Team"))
        self.l4.setText(_translate("Dialog", "Select Team"))
        self.l5.setText(_translate("Dialog", "Select Match"))
        self.l2.setText(_translate("Dialog", "Players"))
        self.l3.setText(_translate("Dialog", "Points"))
        self.pbtn.setText(_translate("Dialog", "Calculate Score"))


    def calcScore(self):
        import sqlite3
        cts = sqlite3.connect("Fantasy_cricket.db")
        team = self.cb1.currentText()
        self.lw1.clear()
        sql = "SELECT Players, Value FROM teams WHERE Name='"+team+"'"
        exc = cts.execute(sql)
        rec = exc.fetchone()
        item = rec[0].split(',')
        self.lw1.addItems(item)
        teamttl=0
        self.lw2.clear()
        for i in range(self.lw1.count()):
            nm=self.lw1.item(i).text()
            exc=cts.execute("SELECT * FROM match WHERE Player='"+nm+"';")
            row=exc.fetchone()
            batscore=int(row[1]/2)
            if batscore>=50:
                batscore+=5
            if batscore>=100:
                batscore+=10
            if row[1]>0:
                sr=row[1]/row[2]
                if sr>=80 and sr<100:
                    batscore+=2
                if sr>=100:
                    batscore+=4
            batscore+=row[3]
            batscore+=2*row[4]
            
            bowlscore=row[8]*10
            if row[8]>=3:
                bowlscore+=5
            if row[8]>=5:
                bowlscore+=10
            if row[7]>0:
                er=6*row[7]/row[5]
                
                if er<=2:
                    bowlscore+=10
                elif er>2 and er<=3.5:
                    bowlscore+=7
                elif er>3.5 and er<=4.5:
                    bowlscore+=4
            fieldscore=(row[9]+row[10]+row[11])*10            
            ttl=batscore+bowlscore+fieldscore
            self.lw2.addItem(str(ttl))
            teamttl=teamttl+ttl
        self.le1.setText(str(teamttl))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
